In [1]:
import numpy as np # for doing most of our calculations
import matplotlib.pyplot as plt# for plotting
from cs231n.data_utils import load_CIFAR10 # function to load the CIFAR-10 dataset.

# Load matplotlib images inline
%matplotlib inline

# These are important for reloading any code you write in external .py files.
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

In [2]:
# Set the path to the CIFAR-10 data
cifar10_dir = '/home/alon/school/c247a/datasets/cifar-10-batches-py' # You need to update this line
X_train, y_train, X_test, y_test = load_CIFAR10(cifar10_dir)

# As a sanity check, we print out the size of the training and test data.
print('Training data shape: ', X_train.shape)
print('Training labels shape: ', y_train.shape)
print('Test data shape: ', X_test.shape)
print('Test labels shape: ', y_test.shape)

Training data shape:  (50000, 32, 32, 3)
Training labels shape:  (50000,)
Test data shape:  (10000, 32, 32, 3)
Test labels shape:  (10000,)


In [3]:
from nndl import KNN

In [4]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.9, 0.9]])

cal = A.sum(axis=0)

perc = 100*A/cal

print(perc)

[[94.91525424  0.          2.81509917 88.42652796]
 [ 2.03389831 43.51464435 33.26935381 10.40312094]
 [ 3.05084746 56.48535565 63.91554702  1.17035111]]


In [8]:
B = np.rot90(A[:,:,None],1,(1,2))
C = np.rot90(B,1,(0,1))
print(B.shape)
print(C.shape)
print(np.sqrt(np.sum((B-C)**2, axis=2)).shape)

(3, 1, 4)
(1, 3, 4)
(3, 3)


In [9]:
# Subsample the data for more efficient code execution in this exercise
num_training = 5000
mask = list(range(num_training))
X_train = X_train[mask]
y_train = y_train[mask]

num_test = 500
mask = list(range(num_test))
X_test = X_test[mask]
y_test = y_test[mask]

# Reshape the image data into rows
X_train = np.reshape(X_train, (X_train.shape[0], -1))
X_test = np.reshape(X_test, (X_test.shape[0], -1))
print(X_train.shape, X_test.shape)

(5000, 3072) (500, 3072)


In [14]:
X_train_rot = np.rot90(X_train[:,:,None],1,(1,2))
X_test_rot = np.rot90(np.rot90(X_test[:,:,None],1,(1,2)),1,(0,1))
print(X_train_rot.shape)
print(X_test_rot.shape)

print((np.subtract(X_train_rot,X_test_rot)**2).shape)

#print(np.sqrt(np.sum(np.subtract(X_train_rot,X_test_rot)**2, axis=2)).shape)

(5000, 1, 3072)
(1, 500, 3072)


MemoryError: Unable to allocate 57.2 GiB for an array with shape (5000, 500, 3072) and data type float64

In [17]:
dists = np.sqrt(np.sum(np.subtract(X_test[:,None,:],X_train[None,:,:])**2,axis=-1))

SyntaxError: invalid syntax (<ipython-input-17-f7c9cceb3499>, line 1)

In [40]:
#we want dists[i,j] to be (x_i-y_j)^T(x_i-y_j)
#You can expand this out into the addition of three separate terms.
#Each term can be calculated separately in isolation, and recombined at the end.

print((np.sum(X_test**2, axis=1)).shape)
print((np.sum(X_train**2, axis=1)).shape)
print(X_test.dot(X_train.T).shape)

test_term = np.sum(X_test**2, axis=1).reshape(500,1)
train_term = np.sum(X_train**2, axis=1)
both_term = 2*X_test.dot(X_train.T)

print((test_term+train_term-both_term).shape)

#result = np.sqrt(train_term - both_term)

(500,)
(5000,)
(500, 5000)
(500, 5000)


In [42]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.9, 0.9]])

A_sorted = np.sort(A, axis=1)
print(A_sorted)

[[  0.    4.4  56.   68. ]
 [  1.2   8.   52.  104. ]
 [  0.9   1.8  99.9 135. ]]
